image: docker:latest

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:latest
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week